version: '2.1'
services:
  containers:
    build: .
    volumes:
      - .:/usr/src/app
      - ~/flask-model-deploy/test.db:/usr/src/app/test.db
    ports:
      - "5000:5000"
    environment:
      - DB_PATH:sqlite:///test.db
